language: r
cache: packages
latex: false
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    
r_packages:
  - covr

r_github_packages: stephens999/ashr

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master
